import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { PageTitleHeader } from '../components/pageTitleHeader/PageTitleHeader'
import styles from '../styles/Home.module.css'

export default function About() {

  return (
    <div className={styles.container}>
      <Head>
        <title>About | NEXT JS DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitleHeader title="about this demo" navigation={true}/>

    </div>
  )
}
