import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [isLoading, setIsLoading] = useState(true)

  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT JS DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Link href='/graduates'>View all graduates ... </Link>


    <p>This is a test button to show state</p>
    {isLoading ? <button onClick={()=>{setIsLoading(!isLoading)}}>Click me to start loading</button> : <p onClick={()=>{setIsLoading(!isLoading)}}>loading ...</p>}
    </div>
  )
}
