import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { PageTitleHeader } from '../components/pageTitleHeader/PageTitleHeader'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [name, setName] = useState('... wait ... who are you?')

  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT JS DEMO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <PageTitleHeader title="next js demo home" navigation={false}/>


    <div className={styles.introArea}>
      <h4>Hey! Welcome {name}</h4>
      <input onChange={(e)=>{setName(e.target.value)}} type="text" placeholder='enter your name' />
    </div>

    <div className={styles.homeBody}>
      <div className={styles.options}>
      <Link href='/articles'>
        <div className={styles.option}>
          view all articles 
        </div>
      </Link>
      <Link href='/about'>
        <div className={styles.option}>
          view about
        </div>
      </Link>
      </div>
    </div>
    </div>
  )
}
